# Custom Language File for Launcher Customizer

[ejs.app]
title = "HSFabric Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/xjqh12/HSFabricLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/xjqh12/HSFabricLauncher"
supportLink = "https://github.com/xjqh12/HSFabricLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO HSFabric Launcher"
welcomeDescription = ""
welcomeDescCTA = ""
