[ejs.landing]
updateAvailableTooltip = "업데이트 가능"
usernamePlaceholder = "사용자이름"
usernameEditButton = "편집"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "모장 상태"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "Non&nbsp;필수"
newsButton = "뉴스"
launchButton = "플레이"
launchButtonPlaceholder = "&#8226; 서버를 선택하지 않았습니다"
launchDetails = "Please wait.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "Checking for News.."
newsErrorFailedSpan = "뉴스를 로드하지 못했습니다."
newsErrorRetryButton = "다시 시도하십시오"
newsErrorNoneSpan = "뉴스 없음"

[ejs.login]
loginCancelText = "취소"
loginSubheader = "마인크래프트 로그인"
loginEmailError = "* 유효하지 않은 값"
loginEmailPlaceholder = "이메일 또는 ID"
loginPasswordError = "* 필수"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊으 셨나요?"
loginRememberMeText = "remember me?"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Need an Account?"
loginPasswordDisclaimer1 = "귀하의 비밀번호는 mojang으로 직접 전송되며 절대 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName} Mojang AB와 제휴하지 않습니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인 옵션"
loginWithMicrosoft = "마이크로소프트 로그인"
loginWithMojang = "모장 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "사용가능 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정 선택"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런쳐"
navAbout = "About"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "새 계정을 추가하거나 기존 계정을 관리하세요."
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ Microsoft 계정 추가"
mojangAccount = "모장"
addMojangAccount = "+ Mojang 계정 추가"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "게임 실행과 관련된 옵션입니다."
gameResolutionTitle = "게임 해상도"
launchFullscreenTitle = "전체 화면으로 실행합니다."
autoConnectTitle = "실행 시 서버에 자동으로 연결됩니다."
launchDetachedTitle = "런처에서 분리된 게임 프로세스를 실행합니다."
launchDetachedDesc = "게임이 분리되지 않은 경우 런처를 닫으면 게임도 닫힙니다."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드를 활성화 또는 비활성화합니다."
switchServerButton = "스위치"
requiredMods = "필수 모드"
optionMods = "선택적 모드"
dropinMods = "드롭인 모드"
addMods = "모드 추가"
dropinRefreshNote = "(새로 고침은 F5)"
shaderpacks = "쉐이더팩"
ShaderpackDesc = "셰이더를 활성화 또는 비활성화합니다. 셰이더는 강력한 설정에서만 원활하게 실행됩니다. 여기에 사용자 정의 팩을 추가할 수 있습니다."
selectShaderpack = "셰이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "Java 구성 관리(고급)."
memoryTitle = "메모리"
maxRAM = "최대 RAM"
minRAM = "최소 RAM"
memoryDesc = "권장되는 최소 RAM은 3GB입니다. 최소값과 최대값을 동일한 값으로 설정하면 지연이 줄어들 수 있습니다."
memoryTotalTitle = "전체"
memoryAvailableTitle = "사용 가능"
javaExecutableTitle = "Java 실행 파일"
javaExecSelDialogTitle = "Java 실행 파일 선택"
javaExecSelButtonText = "파일 선택"
javaExecDesc = "Java 실행 파일은 게임 실행 전에 검증됩니다."
javaPathDesc = "경로는 <strong>{pathSuffix}</strong>로 끝나야 합니다."
jvmOptsTitle = "추가 JVM 옵션"
jvmOptsDesc = "런타임 시 JVM에 제공되는 옵션입니다. <em>-Xms</em> 및 <em>-Xmx</em>는 포함되어서는 안 됩니다."
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처 자체와 관련된 옵션입니다."
allowedPrereleaseTitle = "사전 출시 업데이트를 허용합니다."
allowedPrereleaseDesc = "사전 릴리스에는 완전히 테스트되지 않았거나 통합되지 않았을 수 있는 새로운 기능이 포함되어 있습니다.<br>사전 릴리스 버전을 사용하는 경우 이는 항상 사실입니다."
dataDirectoryTitle = "데이터 디렉터리"
selectDataDirectory = "데이터 디렉토리 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일과 로컬 Java 설치는 데이터 디렉토리에 저장됩니다.<br>스크린샷과 월드 저장은 해당 서버 구성에 대한 인스턴스 폴더에 저장됩니다."
aboutTabHeaderText = "정보"
aboutTabHeaderDesc = "현재 버전에 대한 정보 및 릴리스 노트를 봅니다."
aboutTitle = "{앱 이름}"
stableRelease = "안정적인 릴리스"
versionText = "버전"
sourceGithub = "소스(GitHub)"
support = "지원하다"
devToolsConsole = "DevTools 콘솔"
releaseNotes = "릴리스 노트"
changelog = "변경 로그"
noReleaseNotes = "릴리스 노트 없음"
viewReleaseNotes = "GitHub에서 릴리스 노트 보기"
launcherUpdatesHeaderText = "런처 업데이트"
launcherUpdatesHeaderDesc = "런처 업데이트를 다운로드, 설치 및 검토하세요."
checkForUpdates = "업데이트 확인"
whatsNew = "새로운 소식"
updateReleaseNotes = "릴리스 노트 업데이트"

[ejs.waiting]
waitingText = "마이크로소프트를 기다리고 있다.."

[ejs.welcome]
continueButton = "계속"


[js.discord]
waiting = "클라이언트를 기다리고 있습니다.."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "마이크로소프트 로그인"
microsoftLogoutTitle = "마이크로소프트 로그아웃"

[js.login]
login = "로그인"
loggingIn = "LOGGING IN"
success = "성공"
tryAgain = "다시 시도하십시오"

[js.login.error]
invalidValue = "* 잘못된 값"
requiredValue = "* 필수"

[js.login.error.unknown]
title = "로그인 중 알 수 없는 오류"
desc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 참조하세요."

[js.landing.launch]
pleaseWait = "잠깐만 기다려주세요.."
failureTitle = "실행 중 오류 발생"
failureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "선택한 계정이 없습니다."

[js.landing.selectedServer]
noSelection = "선택된 서버 없음"
loading = "로드 중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
Checking = "시스템 정보를 확인하는 중입니다.."
noCompatibleJava = "호환되는<br>Java 설치를 찾을 수 없습니다."
installJavaMessage = "Minecraft를 시작하려면 Java {major}의 64비트 설치가 필요합니다. 복사본을 설치하시겠습니까?"
installJava = "자바 설치"
installJavaManually = "수동으로 설치"
javaDownloadPrepare = "Java 다운로드 준비 중.."
javaDownloadFailureTitle = "Java 다운로드 중 오류 발생"
javaDownloadFailureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
javaRequired = "실행하려면<br>Java가 필요합니다."
javaRequiredMessage = '실행하려면 Java {major}의 유효한 x64 설치가 필요합니다.<br><br><a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#를 참조하세요. Java를 수동으로 설치하는 방법에 대한 지침은 manual-installing-a-valid-version-of-java">Java 관리 가이드</a>를 참조하세요.'
javaRequiredDismiss = "이해합니다"
javaRequiredCancel = "뒤로 가기"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 배포판을 찾지 못했습니다."
javaDownloadCorruptedError = "다운로드한 JDK에 잘못된 해시가 있습니다. 파일이 손상되었을 수 있습니다."
extractingJava = "Java 추출 중"
javaInstalled = "자바가 설치되었습니다!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보를 불러오는 중.."
fatalError = "치명적인 오류"
CouldToLoadDistributionIndex = "배포 색인의 복사본을 로드할 수 없습니다. 자세한 내용은 콘솔(CTRL + Shift + i)을 참조하십시오."
pleaseWait = "잠깐만 기다려주세요.."
errorDuringLaunchTitle = "실행 중 오류 발생"
seeConsoleForDetails = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
validatingFileIntegrity = "파일 무결성을 확인하는 중.."
errorDuringFileVerificationTitle = "파일 확인 중 오류 발생"
downloadingFiles = "파일 다운로드 중.."
errorDuringFileDownloadTitle = "파일 다운로드 중 오류 발생"
preparingToLaunch = "실행 준비 중.."
launchGame = "게임 시작 중.."
launchWrapperNotDownloaded = "기본 파일인 LaunchWrapper를 제대로 다운로드하지 못했습니다. 결과적으로 게임을 시작할 수 없습니다.<br><br>이 문제를 해결하려면 바이러스 백신 소프트웨어를 일시적으로 끄고 게임을 다시 시작하십시오.<br>< br>시간이 있으시면 <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">문제를 제출</a>하고 어떤 바이러스 백신 소프트웨어를 사용하는지 알려주세요. 그들에게 연락해서 문제를 바로잡도록 노력하세요."
doneEnjoyServer = "완료. 서버를 즐겨보세요!"
checkConsoleForDetails = "자세한 내용은 콘솔(CTRL + Shift + i)을 확인하세요."

[js.landing.news]
checking = "뉴스를 확인하는 중"

[js.landing.discord]
loading = "게임 로딩 중.."
joining = "HSServer로 항해 중입니다!"
joined = "탐험하세요!"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "뭔가 잘못되었습니다"
errorMessage = "Microsoft 인증에 실패했습니다. 다시 시도하십시오."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "뭔가 잘못되었습니다"
errorMessage = "Microsoft 로그아웃에 실패했습니다. 다시 시도하십시오."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "선택한 계정 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "경고<br>이것은 귀하의 마지막 계정입니다"
lastAccountWarningMessage = "런처를 사용하려면 최소한 하나의 계정에 로그인해야 합니다. 이후에는 다시 로그인해야 합니다.<br><br>로그아웃하시겠습니까?"
verifyButton = "확실해요"
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "사용자 이름"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "선택한 계정 ✓"
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "제거"
deleteFailedTitle = "<br>드롭인 모드 {fullName}을(를) 삭제하지 못했습니다."
deleteFailedMessage = "파일이 사용 중이 아닌지 확인하고 다시 시도하십시오."
failedToggleTitle = "<br>하나 이상의 드롭인 모드를 전환하지 못했습니다."
okButton = "좋아요"

[js.settings.serverListing]
mainServer = "메인 서버"

[js.settings.java]
selectedJava = "선택됨: 자바 {version} ({vendor})"
invalidSelection = "잘못된 선택"
requiresJava = "필요 자바 {major} x64."
availableOptions = "자바에 사용 가능한 옵션 {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "시험판"
stableReleaseTitle = "안정적인 릴리스"
releaseNotesFailed = "릴리스 노트를 로드하지 못했습니다."

[js.settings.updates]
newReleaseTitle = "새 릴리스 사용 가능"
newPreReleaseTitle = "새로운 시험판 출시 가능"
downloadingButton = "다운로드 중.."
downloadButton = 'GitHub에서 다운로드<span style="font-size: 10px;color: grey;text-shadow: none !important;">런처를 닫고 dmg를 실행하여 업데이트하세요.</span>'
lateVersionTitle = "최신 버전을 실행 중입니다."
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "업데이트 확인 중.."

[js.uibinder.startup]
fatalErrorTitle = "치명적인 오류: 배포 색인을 로드할 수 없습니다."
fatalErrorMessage = "배포 인덱스를 다운로드하기 위해 서버에 연결을 설정할 수 없습니다. 로드할 수 있는 로컬 복사본이 없습니다. <br><br>배포 인덱스는 최신 서버 정보를 제공하는 필수 파일입니다. 런처를 사용할 수 없습니다. 없이 시작하려면 인터넷에 연결되어 있는지 확인하고 애플리케이션을 다시 시작하세요."
closeButton = "닫기"

[js.uibinder.validateAccount]
failedMessageTitle = "로그인 새로 고침에 실패했습니다."
failedMessage = "<strong>{account}</strong>에 대한 로그인을 새로 고칠 수 없습니다. 다른 계정을 선택하거나 다시 로그인하십시오."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>에 대한 로그인을 새로 고칠 수 없습니다. 다시 로그인하십시오."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "업데이트 확인 중..."
installNowButton = "지금 설치"
checkForUpdatesButton = "업데이트 확인"